# Generated by Django 4.2.10 on 2024-02-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='default_link',
            field=models.URLField(default=''),
        ),
        migrations.DeleteModel(
            name='DefaultLink',
        ),
    ]
