# Generated by Django 4.2.10 on 2024-02-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_client_default_link_delete_defaultlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='default_link',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
