# Generated by Django 4.2.10 on 2024-02-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_client_default_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagewithlink',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
