# Generated by Django 4.2.10 on 2024-02-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_newprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
