# Generated by Django 4.2.10 on 2024-02-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_client_logo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='logo_image',
            new_name='logoimage',
        ),
    ]
